Repository Niemeyer-Research-Group/pyMARS, pull requests merged in 2019-05, with the labels that each got.

#40 Refactor Sensitivity Analysis and Implement DRGASA Reduction Method
  pymars/drg.py
  pymars/drgep.py
  pymars/pfa.py
  pymars/pymars.py
  pymars/sensitivity_analysis.py
  pymars/tests/test_methods.py
Labels: enhancement

#31 Reduced loops in PFA algorithm to improve time complexity
  pymars/pfa.py
Labels: refactor

#37 Initial Testing Suite
  pymars/sensitivity_analysis.py
  pymars/tests/artificial-mechanism.cti
  pymars/tests/eout_artificial-mechanism.cti
  pymars/tests/eout_gri30.cti
  pymars/tests/example_input_artificial.txt
  pymars/tests/inputfiles/example_input_file_bad_float.txt
  pymars/tests/inputfiles/example_input_file_illogical.txt
  pymars/tests/inputfiles/example_input_file_negative_species_values.txt
  pymars/tests/inputfiles/example_input_file_new_order.txt
  pymars/tests/inputfiles/example_input_file_no_close_keyword.txt
  pymars/tests/inputfiles/example_input_file_no_open_keyword.txt
  pymars/tests/inputfiles/example_input_file_no_species_value.txt
  pymars/tests/nore_gri30.cti
  pymars/tests/onere_gri30.cti
  pymars/tests/test_DRGEP_graph_search.py
  pymars/tests/test_create_limbo.py
  pymars/tests/test_create_trimmed_model.py
  pymars/tests/test_dic_lowest.py
  pymars/tests/test_get_rab1.py
  pymars/tests/test_get_rab2.py
  pymars/tests/test_get_rates_drg.py
  pymars/tests/test_graph_search.py
  pymars/tests/test_readInConditions.py
  pymars/tests/test_soln2cti.py
  pymars/tests/test_trim_drgep.py
Labels: enhancement

#41 Added DRGASA test file
  pymars/tests/drgasa_gri30.cti
Labels: bug

#45 Fixes a bug that causes the nodes in the graphs to not always be initalized
  pymars/drg.py
  pymars/drgep.py
  pymars/pfa.py
Labels: bug

#25 Write Plog Reactions
  pymars/soln2cti.py
Labels: enhancement
